{% set name = "catsmoothing" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catsmoothing-{{ version }}.tar.gz
  sha256: 9d629775e5cca037ea75b72360da3a5de8be40f1842b969a255d786053a2485f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.10
    - numpy >=2
    - shapely >=2

test:
  imports:
    - catsmoothing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/catsmoothing
  summary: Smoothing Shapely geometries using CatMull-Rom spline
  doc_url: https://catsmoothing.readthedocs.io
  dev_url: https://github.com/cheginit/catsmoothing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
