{% set name = "catsmoothing" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catsmoothing-{{ version }}.tar.gz
  sha256: 4b991149ce176e2134ba00b7ebd1b91f2c57a0766cf17b4e400a95c92dc70905

build:
  skip: true  # [py<=39]
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pip
  host:
    - python
    - maturin
    - setuptools
    - wheel >=0.29.0
    - pip
  run:
    - python
    - numpy >=2
    - shapely >=2

test:
  imports:
    - catsmoothing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/catsmoothing
  summary: Smoothing Shapely geometries using CatMull-Rom spline
  doc_url: https://catsmoothing.readthedocs.io
  dev_url: https://github.com/cheginit/catsmoothing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
